### ISSUE TITLE
How to pass (return) multiple values to js without them being glued into one string?

### ISSUE THREAD

**Issue by MishaTreedye** [ChrisKnott/Eel#100]
Hi guys and @ChrisKnott ,

Trying to pass 3 values to the js from python, and it tells me that values come as a string, check this out:

My js code:
![image](https://user-images.githubusercontent.com/44478649/51119585-e368f180-181b-11e9-8f76-9ed543afde1c.png)

My Python code:
![image](https://user-images.githubusercontent.com/44478649/51119544-d0eeb800-181b-11e9-8a0e-ac8a48a45541.png)

I am sure that python returns them right. But eel seems to be passing it as one string argument. This is what I am getting after running the code.
![image](https://user-images.githubusercontent.com/44478649/51119378-5756ca00-181b-11e9-832d-0d3f08d6ca2b.png)

P.S. I surely can split the values from a string and use them, but maybe there's something I am doing wrong while using eel? Anything helps!

**Comment by ChrisKnott** [comment]
When you return multiple items from Python it actually returns a single tuple.

You need to change it so your callback function takes a single argument, then index from that.

Like `pts_count = ret[0]` etc

**Comment by dragon-slayer875** [comment]
> When you return multiple items from Python it actually returns a single tuple.
> 
> You need to change it so your callback function takes a single argument, then index from that.
> 
> Like `pts_count = ret[0]` etc

Hello.
I understand what you're saying but can't understand how I am supposed to change them. Please help.

**Comment by samuelhwilliams** [comment]
Hi @dragon-slayer875. Please feel free to open a news issue asking for help and we can take a look. Including your code will help us help you.

**Comment by dragon-slayer875** [comment]
Sorry for the trouble @samuelhwilliams . I resolved the issue just 10 seconds after putting up the comment. 
Thanks for the speedy reply and again sorry for the inconvenience.
