### ISSUE TITLE
Is it possible to change the way eel call JS functions?

### ISSUE THREAD

**Issue by elieobeid7** [ChrisKnott/Eel#106]
I'm using VSCode and their python linter but this is a problem with all IDEs that have linters or some error checking.

Currently, To call a js function from eel, you do

`eel.say_hello_js('connected!')   # Call a Javascript function`

Which gives this error in Pylint

`Module 'eel' has no 'say_hello_js' member`

You see, Pylint can't read JS and so it cannot understand the functions I create, so Pylint is absolutely correct to give this error.

This error is not harmful but imagine you have a big project and 50 errors, you could either keep checking them all to see if there's a real python error besides that error above or you could just say screw that it's all eel, I'm ignoring all errors, it's just annoying.

 if we could make a function or a list that accepts a string, that won't cause any linter to go crazy. Like

`eel.js('say_hello_js') # of some other function name`

or 

`eel.JS['say_hello_js']['connected']`

**Comment by ChrisKnott** [comment]
@elieobeid7 You should be able to add settings to a `.pylintrc` file to suppress these messages.

I think you need to say;
```
[TYPECHECK]
ignored-modules=eel
```

**Comment by elieobeid7** [comment]
Interesting I'll try that out and reopen the issue if it's not fixed, thank you.
