### ISSUE TITLE
Broswer core

### ISSUE THREAD

**Issue by weathon** [ChrisKnott/Eel#109]
I see there is an file called *Chrome.py*, so I have a question that is this project use *Chrome* or just *Chromium*, I think this is a big problem because **Chrome** is **NOT** a open-source software, but **Chromium** is. I think if you use Chrome, you need to change it to Chromium, but if you just use Chromium, you also need to rename the file, or it will make a dispute with the owner of Chrome -- **Google**.
@ChrisKnott

**Comment by ChrisKnott** [comment]
@weathon It works with either Chrome or Chromium but it prefers Chromium if it is installed https://github.com/ChrisKnott/Eel/blob/master/eel/chrome.py#L46

I think the file was named when it only worked with Chrome

**Comment by weathon** [comment]
If it is runing with some broswer but not a own windows, I am worrying about if some one make a page and that page include eel.js, that page ill call python function, and it will be a security issue.

**Comment by weathon** [comment]
I am sorry about my English is not good.

**Comment by weathon** [comment]
@ChrisKnott
