### ISSUE TITLE
Language Support

### ISSUE THREAD

**Issue by weathon** [ChrisKnott/Eel#112]
I am a Chinese, I want to make a software with Chinese, but when I try to return a json include Chinese from python to js, it give me an Error.

My python: 3.7.2

**Comment by samuelhwilliams** [comment]
Hi weathon. Could you please share the error message you're seeing? Thanks.

**Comment by weathon** [comment]
I am sorry about that I cannot copy the information from my OS. But I know it might be an encode error.( The thibg I return is a json)

**Comment by weathon** [comment]
I am sorry about that I cannot copy the information from my OS. But I know it might be an encode error. But I have already set my file-encode to utf-8.

**Comment by weathon** [comment]
OK, I know what is the problem.

**Comment by samuelhwilliams** [comment]
Is it a problem other people are likely to have? If so can you share details and how you fixed it?

**Comment by weathon** [comment]
OK, finally I found that it’s not an encode problem. It is an problem because the json. The json in js and in python have some different.
In js, you can write json’s key without quotation mark, but in python you cannot. So if you return an json write without quotation mark it will be error.
