### ISSUE TITLE
Return Value

### ISSUE THREAD

**Issue by weathon** [ChrisKnott/Eel#114]
When I use js to call a python function, and I give a return value . But when I want to get this value in js, it give me an object but bot the data. Even I try to use `let a = awite eel.py_function()():` , if I use `console.log` ro output it, it work, but when I do something else (like return it to another **js** function, it doesn’t work.

**Comment by ChrisKnott** [comment]
You really need to share your code otherwise it's almost impossible to know what's going on.

Do the examples work for you like this one https://github.com/ChrisKnott/Eel/tree/master/examples/04%20-%20file_access

**Comment by weathon** [comment]
The example work.

**Comment by weathon** [comment]
This is mr code
https://github.com/weathon/New_DM/blob/master/index.html
