### ISSUE TITLE
When pages more than one

### ISSUE THREAD

**Issue by weathon** [ChrisKnott/Eel#115]
If I Have a app has more than one page, however I add /eel.js to any of them, the python program still close when I click a link lead me to another page.

**Comment by ChrisKnott** [comment]
On the default settings this can potentially happen if the new page takes more than 1 second to open the new websocket - do you think that is happening?

It could also be a caching issue if you previously ran it with a version that didn't include /eel.js

Try opening the dev tools before you change pages to confirm whether it is just opening the websocket too slowly and I will explain how to override the default behaviour

**Comment by weathon** [comment]
My page have sone js and css even sone image need to download from Internet, so open it out of 1 sec. maybe happend. Can I chang the time-out seeting? Thabks!

**Comment by ChrisKnott** [comment]
I am just making some changes that will make this easier, will release them soon.

For now, can you download all the files you need and serve them from your web/ folder rather than downloading them each time?

**Comment by weathon** [comment]
OK, thanks. I will try them.

**Comment by weathon** [comment]
I still cannot find the function to change time-out setting.
:-|

**Comment by weathon** [comment]
@ChrisKnott

**Comment by weathon** [comment]
@ChrisKnott Sory, but I still cannot find the timeout setting
