### ISSUE TITLE
Can i run eel app uses default(not chrome/chromium) OS browser if i have chrome/chromium on the board?

### ISSUE THREAD

**Issue by 3dformortals** [ChrisKnott/Eel#116]
good hour...
Can't found keys or commands that eel run my default browser as gui engine.  
And additional question is "what browsers can be runned?". Firefox/vivaldi/etc or need only especial group... for example based on chromium engine.

**Comment by Cran3kill** [comment]
It looks just Chrome and Chromium from what i see in PR #111 commit on browsers.py. Not sure about what "custom" is about in source code in same py file.

**Comment by ChrisKnott** [comment]
Yes, set the mode to anything else e.g. 'default'.

The logic for picking browser is here https://github.com/ChrisKnott/Eel/blob/master/eel/browsers.py#L43

**Comment by 3dformortals** [comment]
> So try `eel.start('home.html', options={'mode': 'default'})`

all works as expected, thanx!
