### ISSUE TITLE
Sometimes when I edit the file in the editor, and re-run this program, the page doesn't change. Even I refresh it, some js file still is old.

### ISSUE THREAD

**Issue by weathon** [ChrisKnott/Eel#118]
Sometimes when I edit the file in the editor, and re-run this program, the page doesn't change. Even I refresh it, some js file still is old.

**Comment by ChrisKnott** [comment]
Trying adding `'chromeFlags': ['--disable-http-cache']` to `options` dict. 

So it would look something like `start('index.html', options={'chromeFlags': ['--disable-http-cache']})`

**Comment by 3dformortals** [comment]
> Sometimes when I edit the file in the editor, and re-run this program, the page doesn't change. Even I refresh it, some js file still is old.

`Ctrl + Shift + Del` in chrome/chromium case and clear browser data can fix this once, but looks like i need trying flags too, that prevent this in the future

**Comment by weathon** [comment]
@ChrisKnott Thank you very much.
