### ISSUE TITLE
Creating new windows

### ISSUE THREAD

**Issue by CombatVolcano** [ChrisKnott/Eel#122]
What is the best way to create a new window? I tried various things like calling init again, trying to specify different ports (though I really don't want a whole new driver)...

Of course one can simply call JS to create a new window pointing at localhost:8000/whatever... but this new window, because of modern browser behavior, has all of the title bar, i.e. the whole chrome UX.

What is the best way to create an eel-like child window?

**Comment by CombatVolcano** [comment]
So you can do this, and it works, but obviously it causes an exception, though you CAN still call back to eel, AND you can still call eel from the original main page, so I don't get why the check is there for same port because everything functions normally...

```
def openNewPage():
    try:
        eel.start('notTheMainPage.html')
    except:
        pass
```

**Comment by ChrisKnott** [comment]
@CombatVolcano I normally do it in Javascript like this  https://github.com/ChrisKnott/Algojammer/blob/master/web/algojammer.js#L26

If you do it like that with geometry specified and `'_blank'` it will not have all the title bar etc.

You could also import `eel.browsers` and call `open()` yourself (see how it is done internally here https://github.com/ChrisKnott/Eel/blob/master/eel/__init__.py#L120 )

I think this should probably be added to the public API for Eel (`eel.open()` maybe) at some point, thanks for raising it.

**Comment by CombatVolcano** [comment]
So I have noticed that in the method which I showed for ignoring the exception, the problem is that you can't call JS functions in the new page context, using eel.expose won't allow python to pick up the JS attached to the new page, ostensibly.

I will try the methods you outlined which I am certain are far better: I'm sure that using open() from eel.browsers is the way to go to be able to use exposed functions...

**Comment by CombatVolcano** [comment]
If I try to do it this way,
`eel.browsers.open('mypage.html', options={'mode' : 'chrome-app', 'port' : 8901, "host":"localhost", "chromeFlags" : []})`
then many many windows are spawned, as if it's being called every loop of the main eel or something?
I am confused, but it will continuously open new chrome windows with that page
I tried using if __name__=="__main__" but that didn't stop it
I tried setting a bool, using a global, pageIsAlreadyOpen, but it still continuously opens new browser windows
What is the right way?? I really really need this functionality

**Comment by ChrisKnott** [comment]
Can you link to your actual repository? You can make it private and add just me if you want

**Comment by CombatVolcano** [comment]
Unfortunately this is corporate software and I cannot share it, however I will create a test case using my same methods.
Again thanks so much for this project and your continued support.

**Comment by ChrisKnott** [comment]
I have added a `eel.show()` method which opens windows with the same settings as eel uses internally
