### ISSUE TITLE
Local Server Access

### ISSUE THREAD

**Issue by rose-maria** [ChrisKnott/Eel#123]
I am happy to work with eel, & found that it creates a server with specified host & port. If using python i get the local ip address like **192.168.22.124** , then it works fine in my computer but still i am not able to access this on a device which is on same network using this particular IP address + URL.
This same thing when i try with Apache XAMPP Server, then i can access using that ip address.
So i am sure that there is no issue of firewall, since it would try to restrict XAMPP also, but why PYTHON SERVER is INACCESSIBLE in this particular case ?

**Comment by ChrisKnott** [comment]
Probably the specific port is not open to remote connections. Try running the Eel server on port 80

**Comment by rose-maria** [comment]
A great Thanks Sir
