### ISSUE TITLE
Specify chrome path

### ISSUE THREAD

**Issue by matcool** [ChrisKnott/Eel#131]
Is there any way to manually pass in chrome's executable path?

**Comment by samuelhwilliams** [comment]
In the current release version, you should be able to start chrome from a specific location using the `options` dict passed into `eel.start`. For example:

`eel.start('hello.html', options={"mode": "custom", "args": ['/path/to/chrome']})`

Does that work for you?

**Comment by ChrisKnott** [comment]
Yeah I think it should have internal persistent path variables that are set automatically with the `find_chrome()` methods but can be overridden
