### ISSUE TITLE
Borderless Fullscreen

### ISSUE THREAD

**Issue by oyavuzjr** [ChrisKnott/Eel#137]
For me, the chrome flags "--kiosk" and "--start-fullscreen" don't do anything. I'm trying to make it borderless and full screen so that the application is the only visible thing on the monitor

**Comment by oyavuzjr** [comment]
It was a problem with chrome on the computer I was using

**Comment by falcon7731** [comment]
Could you please say what the problem was. I have the same issue.

**Comment by oyavuzjr** [comment]
> Could you please say what the problem was. I have the same issue.

I was using a public computer at the library when I had this problem, but the same code worked as expected on my own devices including windows mac and linux. My best guess is that chrome was somehow outdated due to the software that comes with the user profile at the library

**Comment by falcon7731** [comment]
I'm running Windows 10 and I've just updated chrome to the latest version but I still can't make it fullscreen. It works when I use cefpython, but that modual is way too confusing for me.
Thanks.

**Comment by aryanmarwaha** [comment]
> I'm running Windows 10 and I've just updated chrome to the latest version but I still can't make it fullscreen. It works when I use cefpython, but that modual is way too confusing for me. Thanks.

Hey, I'm having a problem like that. Did you find a solution to it?
