### ISSUE TITLE
Examples ready-to-use

### ISSUE THREAD

**Issue by projetmbc** [ChrisKnott/Eel#14]
Hello.

It would be great to have directly examples ready-tto-use to see what Eel can do.

PS : do you know https://www.youtube.com/watch?v=V2yy141q8HQ ?

**Comment by ChrisKnott** [comment]
@projetmbc Yes, they are one of my favourite bands, although the name was meant as a pun on "Electron" and "Python" https://en.wikipedia.org/wiki/Electric_eel

I will add some further examples in the future, which show more complete applications
