### ISSUE TITLE
How to debug

### ISSUE THREAD

**Issue by 04fsnape** [ChrisKnott/Eel#145]
Hello,

I have an eel app that uses electron, but I can't figure out how to get the error messages from electron. At the moment I have a problem whereby my custom minimise and close buttons won't work, as I discussed [here](https://stackoverflow.com/questions/56303899/uncaught-referenceerror-require-is-not-defined-electron).

Here is my gui.py file:

```
import eel
import sys

options = {
	'mode': 'custom',
	'args': ['node_modules/electron/dist/electron.exe', '.']
}


@eel.expose
def quit_app():
	sys.exit(0)


if __name__ == "__main__":
	eel.init('web')
	eel.start('html/index.html', options=options)

```

So if you could please show me how to get the error outputs then that would be very useful, thanks.

**Comment by ChrisKnott** [comment]
If the error is Electron side then look in the console (press ctrl+shift+i)

**Comment by 04fsnape** [comment]
@ChrisKnott I tried pressing CTL+SHIFT+I but nothing happened.

**Comment by 04fsnape** [comment]
I fixed it by removing this line from my main.js: `mainWindow.setMenu(null);`. Now I can see the errors, thanks!
