### ISSUE TITLE
Using node.js require in eel

### ISSUE THREAD

**Issue by 04fsnape** [ChrisKnott/Eel#147]
Hello,

I am having some errors in my electron app that I believe are due to how eel deals with electron. My problems are that when I try and create my own minimise and close buttons, it says 

> Uncaught ReferenceError: require is not defined at index.html:137

and 

> Uncaught ReferenceError: require is not defined at initNodeRequire (index.js:123) at index.js:109

when the page is loaded,

then 

> Uncaught ReferenceError: BrowserWindow is not defined at window_minimise (index.js:113) at HTMLButtonElement.onclick (index.html:18)

when I click minimise.

I go into more detail [here](https://stackoverflow.com/questions/56303899/uncaught-referenceerror-require-is-not-defined-electron/56324980#56324980), and I have adapted my JS file to use the code in the answer suggested, except I removed the {} around BrowserWindow.

I tested this function without eel by changing `mainWindow.loadURL('http://localhost:8000/html/index.html')` to `mainWindow.loadFile('web/html/index.html')` and starting it with `npm start`. Then it worked.

I believe the issue is that node features such as `require` do not run in the browser, and since this is retrieving a webpage from the browser it causes the error.

Do you know any way that this can be resolved?

Thanks.

**Comment by 04fsnape** [comment]
Perhaps [browserify](http://browserify.org) is required?

**Comment by ChrisKnott** [comment]
I have encountered this problem, I can't remember exactly how I solved it. I think it you have to set 'nodeIntegration: true' when you make the BrowserWindow.

I am working on "first class" Electron support but I have been massively delayed in releasing it unfortunately because been very busy

**Comment by 04fsnape** [comment]
@ChrisKnott Yes I found a bunch of posts telling me to do that, and I tried it but it didn't solve it. I think it might be a fundamental issue in that node doesn't run in the browser without using something additional such as browserify. However, I'm pretty sure I had it working like it is right now on my old computer about 9 months ago which is strange.

**Comment by 04fsnape** [comment]
Just to make sure it wasn't anything weird that I was doing, I combined the [electron-quick-start](https://github.com/electron/electron-quick-start) repo with your [hello world demo](https://github.com/ChrisKnott/Eel/tree/master/examples/01%20-%20hello_world) and it still gave the same errors.

Here are the changes I made:

`mainWindow.loadURL('http://www.localhost:8000/index.html')` in `main.js`.

```
<script>
	// You can also require other files to run in this process
	require('./renderer.js')
</script>
<script type="text/javascript">
	initNodeRequire();
	const BrowserWindow = nodeRequire('electron').remote;
	
	function window_minimise(){
	  let window = BrowserWindow.getCurrentWindow();
	  window.minimize();
	}
	
	function window_close(){
	  let window = BrowserWindow.getCurrentWindow();
	  window.close();
	}
	
	function initNodeRequire(){
	   window.nodeRequire = require;
	   delete window.require;
	   delete window.exports;
	   delete window.module;
	}
</script>
```
After the body tag in `index.html`. (note, I modified your index.html, not theirs).

And in `hello.py` I did

```
options = {
	'mode': 'custom',
	'args': ['node_modules/electron/dist/electron.exe', '.']
}
...
if __name__ == "__main__":
	eel.init('web')
	eel.start('index.html', options=options)
```

**Comment by ChrisKnott** [comment]
@04fsnape Can you try the new example I just pushed and see if it works?

Press ctrl+shift+i to open dev control, then in the JS control - you should have either `require` or `nodeRequire` defined (depending on which Eel version you have).

**Comment by 04fsnape** [comment]
@ChrisKnott Works perfectly, thanks! I removed 

```
<script>
	// You can also require other files to run in this process
	require('./renderer.js')
</script>
```

from `index.html`, and changed the other script to

```
const BrowserWindow = nodeRequire('electron').remote;

  function window_minimise(){
      var window = BrowserWindow.getCurrentWindow();
      window.minimize();
  }

  function window_close(){
      var window = BrowserWindow.getCurrentWindow();
      eel.quit_app_x();
      window.close();
  }
```

**Comment by stafordtituss** [comment]
For remote to work in the latest version of Electron, you need to add the following to webPreferences:
webPreferences: { enableRemoteModule: true, nodeIntegration: true }
Also, the eel.quit_app_x(); has been used by @04fsnape for his project, hence, that should also be removed, or you might get errors. I know that it's dumb, but I was dumb enough to leave it in.

**Comment by stafordtituss** [comment]
Here is a script for minimizing, maximizing, and closing:
`const BrowserWindow = nodeRequire('electron').remote;

function window_minimize(){
    var window = BrowserWindow.getCurrentWindow();
    window.minimize();
}

function window_maximize(){
    var window = BrowserWindow.getCurrentWindow();
    if(!window.isMaximized()){
        window.maximize();
    }else{
        window.unmaximize();
    }
}

function window_close(){
    var window = BrowserWindow.getCurrentWindow();
    window.close();
}`
