### ISSUE TITLE
Specifying chrome path

### ISSUE THREAD

**Issue by para-dise** [ChrisKnott/Eel#153]
Hi,
Is there any way to specify the chrome path? For example, I'm getting `OSError: Can't find Chrome or Chromium installation` as I have chrome locally installed in a folder.

**Comment by ChrisKnott** [comment]
In  the current version, the easiest way to do this is to use the `'custom'` mode and specify the path the the chrome executable

**Comment by ChrisKnott** [comment]
Ok this is added in the new beta version, which should be release this weekend once I've cleared the PR backlog.

You can now say;
```import eel.browsers
eel.browsers.set_path('chrome', '/path/to/your/exe')```
