### ISSUE TITLE
Error: 404 Not Found

### ISSUE THREAD

**Issue by mvincenzi96** [ChrisKnott/Eel#168]
Hey ya, I know this issue has probably been dealt with before, however I can't find any proper workarounds to it. 

I am getting this message:
`Error: 404 Not Found
Sorry, the requested URL 'http://localhost:8000/main.html' caused an error:

File does not exist.`

Everytime I run a test eel project.
First I had issues with Python displaying a osError because some other program was using port 8000. After I killed that task to leave that port free for eel, it only showed me the message you can see above.

Here's the code:

eeltest.py
`import eel

eel.init('web')
eel.start('main.html')`

main.html
`<p>Hola</p>`

Any help will be very appreciated in advance.

**Comment by inegalf** [comment]
Let me see, the issue here is that probably you forgot to create the folder "web" inside your Eel project. wasn't it this?

**Comment by mvincenzi96** [comment]
Nope. Creating that folder was the first thing I did.

However, I found a workaround. It seems like when I execute the .py file
from Visual Studio Code or CMD, it shows this error. Nevertheless, if I run
it from IDLE, everything works properly.
Not sure of why does it have that behavior but, it works for now if its
executed from IDLE.

**Comment by Proladon** [comment]
Same Problem.
Eel worked before, but when i run the second time suddenly it broken.
Although cleaning the chrome cache, it doesn't work anymore :(

**Comment by samuelhwilliams** [comment]
@mvincenzi96 Are you able to share the full code you're using, e.g. by sharing a link to your git repository? This will let me test this more easily to confirm what's going wrong and help you.

**Comment by onelonlyprogrammer** [comment]
It seems to be cache related. Try running your program after changing to the program directory, then try running the program from somewhere else. If you clear the cache then you'll probably get the same error.

**Comment by axl3blaz3** [comment]
Same issue, please help....

**Comment by axl3blaz3** [comment]
@samuelhwilliams https://github.com/axl3blaz3/Botx2 , this only works on python IDLE and wouldn't work with python.exe , since i am integrating it with automation anywhere RPA tool i need it through python.exe.

**Comment by aadhav-n1** [comment]
@samuelhwilliams @ChrisKnott I too face the same issue. PyInstaller works, `web` folder is there, but it seems to throw the same error as the OP posted here. I hope this issue is resolved soon.

**Comment by aadhav-n1** [comment]
Here is the screenshot of my directories, I hope it helps!

![github-eel-error](https://user-images.githubusercontent.com/53528139/74541447-9ea41280-4f67-11ea-8747-9f31a65457ba.png)

The directory is the same, as suggested in the **README.md** .

I'm using `python3 -m eel app_main.py web --onefile` to build my files.

**Comment by aadhav-n1** [comment]
I found out the solution, **kill all the processes running on that port**. I didn't get any error because it crashed on startup.

Anyone who is stuck here, the **fix** is:
- Kill the processes on the port by using `fuser -k [port_name]/tcp`.
- Build the file using [the steps mentioned here.](https://github.com/samuelhwilliams/Eel#building-distributable-binary-with-pyinstaller)
- Run the executable again! It works now!

This is not related to the **cache** as mentioned above, I tried clearing the cache as well keeping the cache.

**Comment by mvincenzi96** [comment]
> @mvincenzi96 Are you able to share the full code you're using, e.g. by sharing a link to your git repository? This will let me test this more easily to confirm what's going wrong and help you.

https://github.com/samuelhwilliams/Eel/issues/168#issuecomment-510708042

**Comment by mvincenzi96** [comment]
> It seems to be cache related. Try running your program after changing to the program directory, then try running the program from somewhere else. If you clear the cache then you'll probably get the same error.

https://github.com/samuelhwilliams/Eel/issues/168#issuecomment-510708042

**Comment by jcpaniaguas** [comment]
I already had have the same problem and i was be able to solved. The way i've solved is just change the line:

`eel.init('web')` 

to the absolute path, like

`eel.init('C:/.../web')` where my web folder is

I hope that helps!

**Comment by sarthak-creator** [comment]
**After the new update, you need to provide the location of html file.
For your program you can do:**

eel.start("web/main.html")

**It worked for me 
Hope it works for you.**

**Comment by seanyse** [comment]
My issue was that i had a python exe that I already built with pyinstaller that was running in the background, even though it was closed out. So it was taking up the port and refusing any new connections. Once i opened task manager to kill the exe I was able to run it fine. 
Hope this helps!

**Comment by cnshu** [comment]
I have found solution to this particular problem : ) - just do two things first make sure that your main html file name is  **index.html** and other is that the file must exist in the specific location where you have specified in `eel.init("foldername")` function (☞ﾟヮﾟ)☞ and the problem is solved

**Comment by 123-del** [comment]
Just change it to any other port instead of 8000.
eel.start ("index.html", port = your port)

**Comment by jpanzolaa** [comment]
import eel
import os

# Set web files folder
eel.init(f'{os.path.dirname(os.path.realpath(__file__))}/web')

**Comment by D4koon** [comment]
Thanks jpanzolaa, using an absolute path was the solution for me to

**Comment by ssimpstauff** [comment]
> import eel import os
> 
> # Set web files folder
> eel.init(f'{os.path.dirname(os.path.realpath(**file**))}/web')

I had to use "__file__" to get my current file. I am also using PyCharm which establishes a venv folder that I mistakingly stored my "web" folder in. 

This made the __file__ path of my main.py file "$project" but my web folder was in "$project/venv/web" so I had to move my web folder up one level in order for the realpath to work

**Comment by usamnbinamjad493** [comment]
i was having that problem too but i just changed
eel.init("web")
to
eel.init("C:\Programing\web") change it to your full path

**Comment by pius-mn** [comment]
This worked for me
```
import eel 
from random import randint 

eel.init("./web") 

# Exposing the random_python function to javascript 
@eel.expose	 
def random_python(): 
	print("Random function running") 
	return randint(1,100) 

# Start the index.html file 
eel.start("index.html")

```
