### ISSUE TITLE
Lose connection after running a program for a long time

### ISSUE THREAD

**Issue by ELFANTROUSSI** [ChrisKnott/Eel#169]
I am using eel to create an interface for a device that should work for 24/24 doing continuous serial communication. But after running the software for a long time I lose the connection . And I see that the browser is trying to reload the web page but it fails and it stops everything.

**Comment by ChrisKnott** [comment]
@ELFANTROUSSI Thank you for checking out Eel, sorry for slow reply.

Your use case it quite unique, it is not something I have tested at all. I think perhaps it could be solved by having a manual refresh of the connection every hour or something. I will look into this next week when I am on holiday and will have some time for programming.

**Comment by ELFANTROUSSI** [comment]
Hi @ChrisKnott,
First, I want to thank you for your wonderfull project EEL.
I found finally that the problem wasn't from the websocket part, but it was from javascript leak of memory. The memory was saturated and the browser crashes, and then the webserver stops also.
I've used the debug option to get some traces of what happens.
