### ISSUE TITLE
How handle errors in eel

### ISSUE THREAD

**Issue by datainvestor** [ChrisKnott/Eel#173]
Lets say the python function wrapped in eel gets incorrect data and then when invoked in JS side it will throw error in python. How can I handle this error on JS side (I want to ultimately display flash messeges when the eel function is giving out errors). 
I tried this
```
try {
        await eel.generatefile($('#file').val())();
    } catch (err) {
        console.log("this not work")
    }
```
 but it doesn't print out console.log even though the generatefile function throws error on python side

**Comment by ChrisKnott** [comment]
This is a fairly hard design problem that I haven't put a lot of thought into yet.

I think it would be possible to catch all exceptions, pass a special message, then raise an exception on the other side... but I don't know if it is a good idea...

It feels like it might be a dangerous thing to do, although I definitely see the attraction, as in your example.

**Comment by datainvestor** [comment]
How I solved this issue was to pass a list to JS side with values that would depend whether there was an error in python side.
In python:
```
    try:
        result=somefunc()
        return ["False",result]
    except Exception as e:
        x = ["True", getattr(e, 'message', str(e))]
        return x
```

Then in JS I would assing the function to variable:

```
let iferror = await eel.func()();
if ( ifer3[0] == "True" )
{ 
    console.log("error")
} else {
//if no error run the function
    iferror
}
```

**Comment by ChrisKnott** [comment]
@datainvestor Yes that's a good solution - essentially like an Option type
