### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by Python-Coder-TR** [ChrisKnott/Eel#176]
I use python 3.7.4  64-bit on windows 10. I am sure i installed eel and maked web folder, main.html  etc correct. But when i run this code:
```python
import eel
eel.init("web")
eel.start("main.html")
```
i have an error:
```python
Traceback (most recent call last):
  File "C:\Users\Foo\Desktop\arayüz\app.py", line 6, in <module>
    eel.start("main.html")
  File "C:\Users\Foo\AppData\Local\Programs\Python\Python37\lib\site-packages\eel\__init__.py", line 100, in start
    brw.open(start_urls, options)
  File "C:\Users\Foo\AppData\Local\Programs\Python\Python37\lib\site-packages\eel\browsers.py", line 33, in open
    chr.run(options, start_urls)
  File "C:\Users\Foo\AppData\Local\Programs\Python\Python37\lib\site-packages\eel\chrome.py", line 12, in run
    stderr=sps.PIPE)
  File "C:\Users\Foo\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Foo\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```
please any help?

**Comment by HuiiBuh** [comment]
This is the exact same issue as #172 (same stack trace).  
And please use the markdown function of github next time. Your code is really hard to read.

**Comment by Python-Coder-TR** [comment]
I am new in github and i dont know how to use markdown. Sorry for this.

**Comment by Python-Coder-TR** [comment]
> I use python 3.7.4 64-bit on windows 10. I am sure i installed eel and maked web folder, main.html etc correct. But when i run this code:
> 
> ```python
> import eel
> eel.init("web")
> eel.start("main.html")
> ```
> 
> i have an error:
> 
> ```python
> Traceback (most recent call last):
>   File "C:\Users\Foo\Desktop\arayüz\app.py", line 6, in <module>
>     eel.start("main.html")
>   File "C:\Users\Foo\AppData\Local\Programs\Python\Python37\lib\site-packages\eel\__init__.py", line 100, in start
>     brw.open(start_urls, options)
>   File "C:\Users\Foo\AppData\Local\Programs\Python\Python37\lib\site-packages\eel\browsers.py", line 33, in open
>     chr.run(options, start_urls)
>   File "C:\Users\Foo\AppData\Local\Programs\Python\Python37\lib\site-packages\eel\chrome.py", line 12, in run
>     stderr=sps.PIPE)
>   File "C:\Users\Foo\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 775, in __init__
>     restore_signals, start_new_session)
>   File "C:\Users\Foo\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1178, in _execute_child
>     startupinfo)
> FileNotFoundError: [WinError 2] The system cannot find the file specified
> ```
> 
> please any help?

I reinstalled chrome and eel. Now it is fine.
