### ISSUE TITLE
Hello from Remi project

### ISSUE THREAD

**Issue by pfalcon** [ChrisKnott/Eel#2]
> The closest Python equivalent to Electron (to my knowledge) is cefpython. It is a bit heavy weight for what I wanted.

Can't speak for Electron, but the closest thing to your project appears to be  https://github.com/dddomodossola/remi . Just FYI.

**Comment by pfalcon** [comment]
> the closest thing to your project 

Right, that's not correct. I meant "closest thing to the Python UI via a browser".

**Comment by ChrisKnott** [comment]
I think you are right, looks like a good project (especially if you don't want to write any HTML/JS). I will look into it.

**Comment by AymanEG** [comment]
Remi is really good, but you can integrate your project with https://github.com/r0x0r/pywebview so you can compile the app as a standalone app just like what Remi did 💯 / 💯

**Comment by ChrisKnott** [comment]
@AymanEG I tried it briefly but it doesn't have great Javascript support so it wasn't simple. I will have another go when I get more time. I agree, it would definitely be nicer to be able to use pywebview.

**Comment by denfromufa** [comment]
pywebview is already working on JS <-> Py built-in bridge:

https://github.com/r0x0r/pywebview/issues/83

**Comment by ChrisKnott** [comment]
@denfromufa Yes, it's theoretically possible but it's not trivial. It doesn't by default load .js files that have been included in the HTML and run them.
