### ISSUE TITLE
Can I build websites with Eel?

### ISSUE THREAD

**Issue by jeffli678** [ChrisKnott/Eel#21]
I briefly read some documents about Eel and found its idea awesome. Besides what is already achieved, I think this idea has better potential. Instead of building a local App, why don't we build a website that can be accessed from everywhere? I know sometimes a local App is better, but I think this choice should be left to the user. So I suggest opening a local browser to be an optional feature and adding support for some kind of authentication. It can be basic HTTP authentication in case I host some private stuff on my VPS.

I tried to test my idea. But Eel cannot install under Python 2. I am not sure if it is compatible with 2 because I see some Todo in the src.

**Comment by jeffli678** [comment]
Hi, I just had a look at the Remi project which seems to satisfy my current requirements. Still, I would encourage you to add the above features. Thanks!

**Comment by ChrisKnott** [comment]
The latest code is compatible with Python 2 but not the version on pypi. I will upload a new version to pypi this evening

**Comment by jeffli678** [comment]
@ChrisKnott I tried to download the latest code and install by myself, but still failed. I will post the error and the method I have tried to fix it later.

**Comment by ChrisKnott** [comment]
@jeffli678 Sure, post your error here.

I've uploaded lastest build to pypi now so `pip install eel` should work

**Comment by jeffli678** [comment]
@ChrisKnott Yes, I have tried. Successfully installed. thx!
