### ISSUE TITLE
Provide information on supported platforms and Python versions in README

### ISSUE THREAD

**Issue by cztomczak** [ChrisKnott/Eel#25]
There is no such information in README and neither on PyPI website. 

I've tested on Ubuntu 14.04 with Python 2.7 and I get Python exception no method "shu.which". With Python 3.6 window shows, but no javascript is executed in neither hello.py nor callbacks.py examples.

**Comment by ChrisKnott** [comment]
@cztomczak Sorry, you are right, it seems like the version of shutil on 2.7 does not have the which() method. It was added in 3.3 and hasn't been backported.

I will try and come up with a fix for this.

**Comment by cztomczak** [comment]
In Python 3.6 on Linux there is another issue. I only see "Hello world" message from Python, so I don't think this works as expected.

**Comment by cztomczak** [comment]
It opens using Google Chrome app window I guess, as I have Google Chrome installed.

**Comment by ChrisKnott** [comment]
What do you see in the browser console? (Press F12 to open)

**Comment by cztomczak** [comment]
Nothing in devtools console. See screenshot below:
![eel-py36-hello](https://user-images.githubusercontent.com/1187415/36562089-1a77a52e-1816-11e8-9180-f970803e4f06.png)

**Comment by ChrisKnott** [comment]
Hmm... very strange, it doesn't even have "Hello from Javascript!" message - do you have something installed that disables JS?

**Comment by cztomczak** [comment]
I have Google Chrome configured with Javascript disabled by default. I enable js on websites on a per site basis.

**Comment by cztomczak** [comment]
For security.

**Comment by ChrisKnott** [comment]
You will need to add localhost:8000 to the whitelist, eel needs javascript in order to communicate between the browser window and the python interpreter

**Comment by cztomczak** [comment]
Thanks, that fixed the problem.
