### ISSUE TITLE
eel.start(<remote url>) ? Not Possible

### ISSUE THREAD

**Issue by AnthoniG** [ChrisKnott/Eel#28]
Loving the project. Been looking for something like this for so long, but did not actually know it lol.

Anyways, I tried doing `eel.start('https://www.mydomain.com')` however it seems that it requires that it pull from `http://localhost.`

I was hoping to integrate offline and online into one application (a Hybrid app if you will).

Is this possible ?

**Comment by Mohamad1994HD** [comment]
I believe, you may have a remote api, and make api calls from the eel server, fetch them in the customized desktop view.

Or it doesn't seem logical ?

**Comment by AnthoniG** [comment]
@Mohamad1994HD Yea, that's definately one way to go and is the more **traditional** way of building things.

However there is a major benefit IMO of opening a hosted **_eel Application_**
_Auto-Update is less painless as everyone is using the same GUI._

Probably more but that's the major one I can think of.

So far I can kinda get it working, but looking into the source it seems it uses http by default (makes sense as that's what `localhost` is)

**Comment by AnthoniG** [comment]
@ChrisKnott What I am thinking of doing is building the UI locally (using Create React APP, Webpack etc), along with the server. Once complete the UI will be then put up onto my own server and then I package the python server as normal and give this to users. Once it starts, it will go to my server and launch the UI from there.

This kind of already works as is, **BUT** it only looks at HTTP and I need it to also look at HTTPS. I could fork it and the logic to use HTTPS, but as it's pretty simple enough perhaps you could add it and then I just re-install it ala PIP ?

I am just testing things out at moment but already loving the light bulb moments this is giving me :)

**Comment by ahopkins** [comment]
@AnthoniG Checkout my PR #33 and Issue #30.

I basically added this, and have it up and running with a webpack served dev environment.

**Comment by ahopkins** [comment]
@AnthoniG If you want to see the project I am using it on right now: https://github.com/sockpuppetapp/sockpuppet

**Comment by AnthoniG** [comment]
Closing as this is covered  in another threa
