### ISSUE TITLE
Electron-Eel Idea

### ISSUE THREAD

**Issue by abulka** [ChrisKnott/Eel#35]
Love this project, however I discovered a few downsides in the deployment dept.

- Requires chrome browser to be installed by the user in the target system
- Packaging with PyInstaller works but displays a console window when launched.  Attempting to specify no console causes app to launch and immediately disappear (still investigating this, but many people have encountered it e.g. https://github.com/pyinstaller/pyinstaller/issues/1804)
- There are no native menus, open file dialog boxes etc.  I can't for example browse for a file in the UI and get its full pathname returned to me (browser sandbox restrictions).  I can't create professional menus.

I'm wondering if a version of this project could be adapted to work with Electron, using Eel's  websocket approach instead of the zerorpc approach taken by https://github.com/fyears/electron-python-example.  I'm finding the latter project powerful but its dependence on zerorpc makes it tricky to deploy.

Plus there are Electric eels, aren't there?  Thoughts?

**Comment by ChrisKnott** [comment]
@abulka Thanks for checking out the project!

To get rid of the console window, include the '--no-console' flag when you are packaging. This is mentioned in the README but it is hidden away at the bottom.

Your other points are very valid, hopefully we will add support for other browsers in the future, particularly Firefox, after that I will look at better integration with Electron front end. In the meantime there are several libraries that can recreate menu bars such Bootstrap and jQueryUI, combining this with calls into Python you should be able to achieve Save/Load behaviour close to native.

**Comment by ChrisKnott** [comment]
@abulka It's possible to use Electron as the front end with the new `custom` mode. See #57
