### ISSUE TITLE
Compiled exe fails with 'Failed to execute script'

### ISSUE THREAD

**Issue by slanska** [ChrisKnott/Eel#41]
On WIndows 8.1 x64, Python 3.6.5 32-bit, after building examples from Eel /examples into single executable with --onefile and --noconsole, I am getting error 'Failed to execute script ABC'. Running script directly by Python is OK. Any clue what might be missing or incorrect here? Thank you in advance.

**Comment by ChrisKnott** [comment]
@slanska where are you seeing that error? Also, is you script called "ABC"? Did you building an .exe without --noconsole and --onefile?

**Comment by brentvollebregt** [comment]
I recommend adding the `-d` flag for debugging output. If you then run the executable from cmd to preserve output you will then be provided with some debugging messages which may help.

Also have you tried updating? `pip install pyinstaller --upgrade`; it has fixes a lot of peoples issues when I have given help on pyinstaller.

**Comment by ChrisKnott** [comment]
I managed to recreate it partly. It crashes for me when using `--noconsole` on the Hello World example.

I am wondering if `--noconsole` excludes the code for `print()`. I works for me otherwise, so apart from that I can't think what the issue is.

I am considering changing to Nuitka for building the executables, I think it is more stable.

**Comment by YusukeSugawara** [comment]
I encountered the same error too (Win 10 Pro x64, Python v3.6.5-64bit, Chrome v67.0.3396.62).

To collect information from stderr, I added the following scripts in head of `hello.py`:

```
import sys
sys.stderr = open("error.log", "a")
```

Then I obtained this log:

```
Traceback (most recent call last):
  File "C:\Users\ .... \Eel\examples\01 - hello_world\hello.py", line 17, in <module>
    eel.start('hello.html', size=(300, 200))    # Start
  File "C:\Users\ .... \Eel\examples\venv\lib\site-packages\eel\__init__.py", line 100, in start
    brw.open(start_urls, options)
  File "C:\Users\ .... \Eel\examples\venv\lib\site-packages\eel\browsers.py", line 33, in open
    chr.run(options, start_urls)
  File "C:\Users\ .... \Eel\examples\venv\lib\site-packages\eel\chrome.py", line 12, in run
    stderr=sps.PIPE)
  File "C:\Users\ .... \AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 667, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "C:\Users\ .... \AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 890, in _get_handles
    p2cread = _winapi.GetStdHandle(_winapi.STD_INPUT_HANDLE)
OSError: [WinError 6] ハンドルが無効です。
```

The last Japanese message means `The handle is invalid`.

Organizing the flow of this trace, a `subprocess.Popen()` without `stdin` argument seems to call `_winapi.GetStdHandle(_winapi.STD_INPUT_HANDLE)` in `_get_handles()` method.
But this makes `OSError` exception for some reason and it crashs eel application. 

I was able to resolve this problem by adding `stdin=sps.PIPE` argument on `Popen` calling. But I don't know whether this is correct way.

**Comment by ChrisKnott** [comment]
@YusukeSugawara Great detective work. I'll add that as default, then maybe expose an option to overwrite with user provided values

**Comment by ChrisKnott** [comment]
Fixed
