### ISSUE TITLE
Passing 0 as the port will give ERR_ADDRESS_INVALID

### ISSUE THREAD

**Issue by brentvollebregt** [ChrisKnott/Eel#42]
For people that want to dynamically assign the port (which is a great idea for this project as the port doesn't have much influence) would set port to 0 like:
```python
eel.start('main.html', options={'port' : 0})
```
Since the browser is opened on line 100 in \_\_init\_\_.py and the server is then started after on line 109, there is no way that the Chrome window can know what the dynamically assigned port is.

So you'll need to start the server first and then call the Chrome window based on the port the server now has, I am not quite sure how to get the port once the server has started though.

**Comment by ChrisKnott** [comment]
@brentvollebregt Good point, port should probably be dynamic by default. I will look into making this change when I get a chance. We will probably have to do something like this https://stackoverflow.com/questions/5085656/how-to-get-the-current-port-number-in-flask or just a normal retry loop with try/catch that picks random ports itself.

Thanks for checking out the project.

**Comment by brentvollebregt** [comment]
Oh wow, that method is a lot cleaner than what I resorted to; I definitely feel the stackoverflow idea is the best approach. I'm currently using the retry loop with try/catch method but felt that something internal would make it a lot better.

The project is awesome by the way; was exactly what I needed.

**Comment by ChrisKnott** [comment]
Thanks, PR accepted
