### ISSUE TITLE
Uncaught ReferenceError: eel is not defined     at script.js

### ISSUE THREAD

**Issue by vv2006-mc** [ChrisKnott/Eel#422]
i added ell.js in html but this error is showing up.

html code:
    <link rel="stylesheet" href="css\style.css">
    <script type="text/javascript" src="ell.js"></script>
    <script src="script.js"></script>

**Comment by ibrahimyaacob92** [comment]
you add that on header or body tag ?

**Comment by thedivyanshuyadav** [comment]
> i added ell.js in html but this error is showing up.
> 
> html code:
> 
> <script type="text/javascript" src="ell.js"></script>
> <script src="script.js"></script>

src should be "/eel.js" instead of "ell.js".

**Comment by Thenujan-0** [comment]
make sure you have linked the eel file before linking the javascript file in html

it should be like this
<script type="text/javascript" src="/eel.js"></script>
<script src="script.js" type="text/javascript"></script>
