### ISSUE TITLE
Cant compilate .py to .exe

### ISSUE THREAD

**Issue by Tapal-lab** [ChrisKnott/Eel#433]
I have a problem compiling my .py file to .exe I followed the directions and used pyInstaller.
My only clue is a strange error occurring during the execution of the file, but I do not know where it comes from.

![python_file](https://user-images.githubusercontent.com/69158636/104851435-456dfd00-58f5-11eb-83af-4bea0f2d5a5d.png)

![html](https://user-images.githubusercontent.com/69158636/104851439-4acb4780-58f5-11eb-8b8a-030d8d67c0c6.png)

![error](https://user-images.githubusercontent.com/69158636/104851445-5159bf00-58f5-11eb-81a4-e82273519528.png)

 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [87]

**Comment by 123456789qiwi** [comment]
python -m eel you_file.py folder_with_html_css_js --onefile
example:
python -m eel main.py WEB --onefile
