### ISSUE TITLE
Change / refresh / close page?

### ISSUE THREAD

**Issue by khoidt** [ChrisKnott/Eel#44]
Hi! Thank you a lot for your work on Eel. I'm wondering if there is a way to open, re-open, or refresh the html page in the very same window? Unfortunately, I couldn't find this information.

I'm using Jinja2 templates for different views. As the program runs, the rendered templates are saved under the same name (`index.html`) and then should to be re-opened. However, doing `ee.start("index.html")` for the second time opens a new window beside the previous one. To add to this, the following OSError appears in the process:
```
OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted: ('localhost', 8000)
2018-05-22T20:00:29Z <Greenlet "Greenlet-0" at 0x1ece5058a48: _process_message({'call': 1.5296098246811638, 'name': 'select_new_t, <geventwebsocket.websocket.WebSocket object at 0x0)> failed with OSError
```
but actually does not seem to affect the program's functionality.

In case if opening another html page in the same window or refreshing it is not possible, is there a way to simply close the old window?

**Comment by ChrisKnott** [comment]
@khoidt

I faced this issue myself recently so I will probably add something to make this easier. For know you can do it in JavaScript with `location.reload(true)` (which you can then wrap in a function and expose).

Similarly you can do things like  `window.close()` although there are some restrictions on when this can be called I think

**Comment by khoidt** [comment]
@ChrisKnott, thanks for your answer. I tried both your suggestions. `location.reload(true)` provides the desired frontend effect, but it also stops the Python process. Do you know if the latter can be avoided? `window.close()` seems not work at all.

**Comment by khoidt** [comment]
For the moment, I managed to get the program to continue running after refreshing the page by changing `sleep(1.0)` to `sleep(10.0)` in `_websocket_close()` ([Github link](https://github.com/ChrisKnott/Eel/blob/e423365afd6fc461f0924d79f3d0e387ab451356/eel/__init__.py#L257)).

**Comment by nba94** [comment]
@ChrisKnott @khoidt Hi there, I'm facing a similar issue here. My application is split into 3 .html parts, whenever I navigate to the .html page initially, all of the functions work fine, however navigating back and forward even once - breaks the functions, is it not possible to have several html pages with `<script>` in each one of them?

**Comment by khoidt** [comment]
Hi @nba94! You can find my code in [this repo](https://github.com/cdli-gh/annotation_assistant). I use Jinja2 templates that are saved as `index.html` on the fly; then this page is refreshed from javascript when new views are needed. With the [slightly adjusted Eel](https://github.com/cdli-gh/annotation_assistant/blob/master/dependencies/Eel.tar.gz) (see my last comment above) I managed to get it to run well. Try installing this Eel instead the default one and see if it works.

**Comment by nba94** [comment]
@khoidt Thanks for your suggestion and input. I have indeed gone ahead and altered the `sleep` from 1.0 to 10.0 prior to commenting my initial comment - but that didn't work out..
I will look into Jinja2 and see maybe that will help me, but I've never used it before, maybe looking at your code will help! Thanks.

**Comment by nba94** [comment]
@ChrisKnott Thanks for your reply. I have downloaded the above shared Eel version by @khoidt and `cd`ed to the top Eel folder and installed by using `pip install -e .` as you suggested. Now I'm running my app and for some reason each time I press a button with a function assigned to it, I get a 'print this page' menu that wants to print the current page out? Also it times out after navigating back and forward between multiple .html pages...

**Comment by nba94** [comment]
@ChrisKnott @khoidt I did a bit more of digging into this and realised that when I start my .py script and initiate the main.html, even though I have buttons on it that navigate users to other `.html`s like profile.html for example, when I check in the developer console of chrome it seems that the ONLY html loaded onto localhost is the main.html, all other htmls are not loaded onto it. Potentially if I create a dependency to upload all of the required htmls onto localhost this issue will be fixed. Just wondering how to do that now.

**Comment by ChrisKnott** [comment]
@nba94
The "print this page" is because the JavaScript is calling `print()` instead of ` console.write()` - an easy mistake to make when switching back and forth between JS and Python

**Comment by nba94** [comment]
@ChrisKnott Thanks you were indeed correct about `print()` and `console.log()` mishap I had.. 
Also I have decided to use JQuery instead of having multiple .html pages, and it works like a charm!!
I wanted to ask a question however - I keep having the same issue over and over again.
When I update either .html or .css file, and run the new app through python, it is not always updated. I sometimes have to force refresh it from within the python script runtime, which is an OK workaround, but it doesn't work like this for CSS for some reason.
Have you come across this before?

**Comment by ChrisKnott** [comment]
I think this is Chrome's default caching behaviour, you can disable the cache by opening dev tools (F12 on PC, cmd+option+J on Mac), going on "Network" and ticking "Disable cache". The cache is only disabled if dev tools is open (but you can have them in a separate window - open the "More" (three dots) menu in the top right)

**Comment by nba94** [comment]
@ChrisKnott Thank you so so much..

**Comment by ChrisKnott** [comment]
@khoidt you can now specify a callback in the options which will be called every time a websocket closes. You can use this to check for a boolean or something for whether you actually want to quit.

**Comment by khoidt** [comment]
@ChrisKnott, thank you! I'm going to use this feature in my next eel script.

**Comment by rvliscano** [comment]
Hello! Thanks a lot for inventing Eel. It's truly wonderful.
I was getting a lot of errors when changing pages. I managed to make everything work as expected by doing some changes to eel.__init__.py file.

In case anyone needs it, please give it a try. If someone spot something wrong that might be with it, please also share it.

All I did was to move away the `_websockets.remove((page, ws))` call from _websocket(ws) to _websocket_close function and slightly modify a couple more of thing in the latter function. Just as follows:
* note that I set `_websocket_close` to accept one additional parameter now.

```
def _websocket_close(page, ws):
    if _on_close_callback is not None:
        sockets = [p for _, p in _websockets]
        _on_close_callback(page, sockets)
    else:
        sleep(5.0)
        _websockets.remove((page, ws))
        if len(_websockets) == 0:
            sys.exit()
```
