### ISSUE TITLE
--kiosk mode to remove the bottom left status bar with chrome?

### ISSUE THREAD

**Issue by GuruPrasaathM** [ChrisKnott/Eel#450]
I can see the status bar in the bottom left whenever anchor links are hovered over, It sometimes messes up the feel of the ui.

I generally workaround this by switching my a tags to labels/buttons with href action on click, But not every one might know it.

Would adding the --kiosk flag to the browser call fix it? If it is feasible, Can you add it as a (optional) feature?

**Comment by samuelhwilliams** [comment]
You can pass the `--kiosk` flag to the browser yourself through `eel.start`'s argument `cmdline_args`.

I don't think we will make this a default setting.

**Comment by GuruPrasaathM** [comment]
Oh, oof, Sorry!
