### ISSUE TITLE
running Eel gives this error

### ISSUE THREAD

**Issue by pyanishjain** [ChrisKnott/Eel#452]
C:\Users\ANISH JAIN\AppData\Local\Programs\Python\Python37\lib\importlib\_bootstrap.py:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
  return f(*args, **kwds)

**Comment by ChrisKnott** [comment]
I think this means you have an old version of ```gevent``` installed
