### ISSUE TITLE
404 Not found, file does not exist

### ISSUE THREAD

**Issue by eliaperantoni** [ChrisKnott/Eel#46]
I have this structure
```
gui.py
web/
  index.html
```

And this inside `gui.py`
```
import eel
eel.init('web')
eel.start('index.html')
```

When I run the script I get this

![screenshot_16](https://user-images.githubusercontent.com/6002855/40881937-3ec6c560-66d4-11e8-965b-1d7fce81fb68.png)

Why is that?

**Comment by ChrisKnott** [comment]
Perhaps the file is called something slightly different? This is what would happen if it was called `index.htm` for example

**Comment by eliaperantoni** [comment]
I will try the examples.
Did copy-paste both the name of the directory and the file in the script though

**Comment by eliaperantoni** [comment]
@ChrisKnott I modified absolutely nothing and this morning it worked ಠ_ಠ

**Comment by Underrooz** [comment]
i'm getting the same error. should i wait till morning ?!

**Comment by ChrisKnott** [comment]
Probably it is some kind of caching issue. I will be pushing changes in the next week or so that should mitigate problems with caching

**Comment by mvincenzi96** [comment]
I am having this issue with the latest version of eel. Mmmmm....

**Comment by shrsulav** [comment]
Hello @ChrisKnott ,
I have written a python script to start the GUI.
And I have made a service file for linux out of it. But when I go to the localhost:port/index.html, it says 400 not found.

But, when I manually run the script from terminal, it works. Can you help me here?

**Comment by aadhav-n1** [comment]
Possible solution here: [Issue #168 ](https://github.com/samuelhwilliams/Eel/issues/168#issuecomment-586332554)

**Comment by einfachWitzlos** [comment]
Hey everyone, I fixed this issue by using os.path and use the full path like so:
`
import eel
import os

dirname = os.path.dirname(__file__)
eel.init(os.path.join(dirname, "www/"))
eel.start("index.html")
`
My folder sturcure is:
gui.py
www/
  index.html
      
It seems to be the usual path problems with Windows systems.
@ChrisKnott maybe have a look at a way to fix this for the different os types or add a note to the readme?

**Comment by evajoe2** [comment]
it work for me  like this:

```
import eel
import os

dirname = os.path.dirname(__file__)

eel.init(dirname)

eel.start('main.html')
```

**Comment by Meet-BVM** [comment]
> Hey everyone, I fixed this issue by using os.path and use the full path like so:
> 
> ```
> import eel
> import os
> 
> dirname = os.path.dirname(__file__)
> eel.init(os.path.join(dirname, "www/"))
> eel.start("index.html")
> ```
> 
> My folder sturcure is: gui.py www/ index.html
> 
> It seems to be the usual path problems with Windows systems. @ChrisKnott maybe have a look at a way to fix this for the different os types or add a note to the readme?


hi i already use this method but not working
