### ISSUE TITLE
Auto-update Eel application from repo

### ISSUE THREAD

**Issue by lthomas122** [ChrisKnott/Eel#462]
Is there anyway to automatically update your eel application from a repository after packaging the app for distribution?

**Comment by rahmatagungj** [comment]
of course, you can make it.

**Comment by grokwithrahul** [comment]
If you are using cx_freeze to compile and package your app, try esky: https://pypi.org/project/esky/
If you are using pyinstaller, [pyupdater](https://www.pyupdater.org/) should work, although personally I have never used it
