### ISSUE TITLE
Can Eel be used to make apps which require internet connection?

### ISSUE THREAD

**Issue by Adeel-Intizar** [ChrisKnott/Eel#463]
Hello, I want to develop an application which will require internet connection for a short period of time, is it possible to develop it using eel?

**Comment by rahmatagungj** [comment]
of course you can, you can use the method of checking the internet connection when the EEL is loaded. if the user's status is online, the EEL operation will continue and when offline, the EEL will stop.

**Comment by Adeel-Intizar** [comment]
Thank you for your help

**Comment by Adeel-Intizar** [comment]
@rahmatagungj how to check online status with eel?
