### ISSUE TITLE
after packaging an eel app its taskbar icon is not the one I selected but the chrome icon

### ISSUE THREAD

**Issue by marcomaiocchi** [ChrisKnott/Eel#469]
I packaged a desktop app selecting a custom icon. The icon shows up correctly only in windows explorer. In the taskbar my app has the chrome app icon. How can I use my custom icon also on the taskbar when using eel?

**Comment by ChrisKnott** [comment]
Try putting the icon in the `web` folder, named `favicon.ico`.

**Comment by marcomaiocchi** [comment]
Thanks for the reply! Good point.. I added the favicon.ico to the web folder and also tried to add 

`<link rel="icon" href="favicon.ico">`

in the html header but it doesn't have any effect on my packaged desktop app (or even on the app obtained by simply running the .py script with eel). The icon doesn't show up in the taskbar and neither on the top left corner of the app.

**Comment by marcomaiocchi** [comment]
By doing the above, what changes is just the html opened in the chrome browser. Now this one has the correct icon on the tab next to the name. Still not able to show the icon via eel though.

**Comment by marcomaiocchi** [comment]
Actually Chris' solution worked. My machine was probably caching old icons and so I couldn't see the change right away. After refreshing the icons db on my windows 10, I can see the icon showing up both on taskbar and top left corner. Thank you!
