### ISSUE TITLE
Using firebase with eel causing problems with closing browser window

### ISSUE THREAD

**Issue by shourikan** [ChrisKnott/Eel#472]
I am using firebase with my python app that uses eel for frontend. However, when I try closing the window of the browser, the app won't close like it normally does and instead, it opens another 6 or so new windows.

I was thinking maybe WebSockets have something to do with that. Any idea how to handle this eel + firebase combination?

Thanks

**Comment by ChrisKnott** [comment]
Short answer - no, sorry! Certainly it is not Eel opening the new browser windows, unless you have written something to do that yourself.
