### ISSUE TITLE
How to run 09 - Eelectron-quick-start example

### ISSUE THREAD

**Issue by Kubis10** [ChrisKnott/Eel#487]
**Describe the problem**
I have problem with running electron with eel.
I was trying to run it by building it with `python -m eel file.py web -y` and with electron building `npm install --save-dev @electron-forge/cli` `npx electron-forge import` and then `npm start or ` or `npm run make` but when I click exe from PyInstaller app doesn't want to open only terminal show up for half a second and that's all and when I click exe from electron site is always empty like it render empty file whatever I do. 

**Code**
Code is the same as in example

**Desktop :**
 - OS: Windows10
 - chrome

**Comment by crunchstefan** [comment]
i managed to make it run by changing the hello.py to start the main.js instead of hello.html (line 19):
eel.start('main.js', mode='custom', cmdline_args=['node_modules/electron/dist/electron', '.'], port=8000)

and then run the program with python hello.py (instead of npm start)

**Comment by Kubis10** [comment]
Thanks, it works. So is there any way to built it with pyinstaller or I need to run it by `py hello.py` ?

**Comment by crunchstefan** [comment]
I didn't manage to make it work yet, but i'm sure it's possible. Somehow i
need to figure out how to include electron in the build. I know i once
stepped over an article that explained the process. If you find out how to
make it work, please let me know.

**Comment by Kubis10** [comment]
https://medium.com/@abulka/electron-python-4e8c807bfa5e I think this will help
