### ISSUE TITLE
MIME type is text/plain

### ISSUE THREAD

**Issue by Kirynn** [ChrisKnott/Eel#49]
Hey! I love using eel so far, its been so simple to get going.

I'm trying to use vue with eel and when importing via type="text/module" im getting an error in my javascript console saying: 

> Failed to load module script: The server responded with a non-JavaScript MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.

Is there anyway to change the mime type? I checked the bottle reference and it looks like there is a way but when I tried to implement it by changing the _static() method I got no change.

**Comment by ChrisKnott** [comment]
Yes, I can change this, thanks for pointing it out

**Comment by ChrisKnott** [comment]
Fixed
