### ISSUE TITLE
eel.js:1 Uncaught ReferenceError: eel is not defined at eel.js:1

### ISSUE THREAD

**Issue by baris-inandi** [ChrisKnott/Eel#497]
[Linux, Google Chrome (latest),  using Eel v0.14.0 on Python 3.8.6]

so I imported my scripts inside `<head>` like this: 
```
<head>
    <script src="./eel.js" type="module"></script>
    <script src="./main.js"></script>
</head>
```
main.js:
```
function py(){
    eel.hello()
}
```
Python:
```
import eel
@eel.expose
def hello():
    print("Hello")
```

When I run the program, this shows up on the console: 
```
Uncaught ReferenceError: eel is not defined
    at eel.js:1
```
![image](https://user-images.githubusercontent.com/68742481/121677435-8641fa80-cabe-11eb-804e-50e6c6c5b768.png)

And when I try to run the function py() through a button click, it still throws the same error:
```
main.js:1 Uncaught ReferenceError: eel is not defined
    at py (main.js:11)
    at HTMLButtonElement.onclick (index.html:23)
```
What might be causing this issue? 

ps: I also tried running the hello world example I downloaded from the repo which also doesn't work because of the same problem.

**Comment by jvanmelckebeke** [comment]
You should include eel like this:
```html
<head>
    <script src="/eel.js" type="module"></script>
    <script src="./main.js"></script>
</head>
```

Note the path: `/eel.js` instead of `./eel.js`

**Comment by baris-inandi** [comment]
i'll try, thanks

**Comment by nevox12** [comment]
> You should include eel like this:
> 
> ```
> <head>
>     <script src="/eel.js"></script>
>     <script src="./main.js"></script>
> </head>
> ```
> 
> Note the path: `/eel.js` instead of `./eel.js`

thank you very much  i change  'eel.js' to '/eel.js' and it works
