### ISSUE TITLE
Can't install on Python 2.7.14 (Anaconda)

### ISSUE THREAD

**Issue by juanfcocontreras** [ChrisKnott/Eel#5]
I get this error when I try to install on Python 2.7

```
Collecting eel
  Downloading Eel-0.7.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/ff/nh987tyd5jgbzygkb6zm3d200000gn/T/pip-build-yPnvk2/eel/setup.py", line 14, in <module>
        long_description=open('README.md', encoding='utf-8').readlines()[1],
    TypeError: 'encoding' is an invalid keyword argument for this function
```

I think it has a straightforward solution.

**Comment by ChrisKnott** [comment]
Yes, there's nothing that specifically needs python3, I just didn't want to pollute the codebase just yet with python2 stuff.

For 1.0.0 I will try and support python2

**Comment by cclauss** [comment]
Can it be somewhere in the README that Python 2 is not currently supported?

**Comment by hargoniX** [comment]
i guess we can close this now?

**Comment by ChrisKnott** [comment]
I think I'll close it once 2.7 is supported, it shouldn't be too hard.

**Comment by ChrisKnott** [comment]
This should work now, although I recommend migrating to Python 3 https://pythonclock.org
