### ISSUE TITLE
Fix lag and page flash?

### ISSUE THREAD

**Issue by VellichorPrism** [ChrisKnott/Eel#508]
**Describe the problem**
Hello! In my web folder I have a few different HTML files for different pages. In the example video and image attached here, I am starting on one page and clicking an element that directs me to a different page. As you can see in the video, the transition looks very laggy and buggy, with a page flash and different things going on. The image I supplied shows the frame by frame transition breakdown. When I open my HTML files in Chrome regularly (not initiated by eel), the page transitions are instant and clean, and you won't see any loading or flashing going on. But, once I started using eel to implement my python back-end, this problem started. Some things that might be useful to know is that I am using TTF sources for my font, and SVG images for my icons. I also tried preloading my fonts, CSS, and Javascript, but that didn't change anything.

If anyone has an idea how to prevent these page flashes, I would greatly appreciate the help. The page flashing and lag happens no matter which page the transition is to. I would like to get it to work just like when I open the HTML in Chrome regularly. Thank you!

Edit: Solved by using Electron. I still don't know why using Chrome caused page flicker....
 
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91

**Comment by ChrisKnott** [comment]
@VellichorPrism Thanks for submitting this.

There's a fundamental tension in Eel, in that part of the reason it's so easy to get going is it offloads so much of the work to the browser. We also make (as the default at least) as little assumptions as possible about that browser.

The downside of this is that the illusion of being a native GUI app can be pretty thin.

That said, from what you've described there should be no reason for the particular artefacts you encountered and it's something I'd hope to eliminate in an (eventual) performance review.
