### ISSUE TITLE
Customising the title bar

### ISSUE THREAD

**Issue by 04fsnape** [ChrisKnott/Eel#51]
Hi,

I was wondering if it would be possible to change the colour of the title bar?

Thanks.

**Comment by ChrisKnott** [comment]
It might be possible by using --user-data-dir flag to set a custom Theme https://support.google.com/chrome/forum/AAAAP1KN0B0WBYijeuKaTw/?hl=en

**Comment by 04fsnape** [comment]
To be honest I have no idea how to do that... But it is reallyyy bugging me since my GUI is very bright and the grey of the title bar really stands out and is quite ugly. I'd very much like to change it to #f7f7f7.

Is there any chance you could have a go at helping me do that? Even if it is after the football aha.

**Comment by ChrisKnott** [comment]
Firstly you have to use something like this to make a Theme - https://chrome.google.com/webstore/detail/theme-creator/akpelnjfckgfiplcikojhomllgombffc?hl=en

**Comment by 04fsnape** [comment]
@ChrisKnott I did that using https://www.themebeta.com/chrome-theme-creator-online.html. I basically set every background colour to be #f7f7f7 just in case. It generated a ZIP folder which contained a folder containing some images, and a manifest.json. I extracted that folder, placed it in the same directory as my python script. Here is the manifest.json:

```
{"name":"ThemeBeta.com","version":"1.0","description":"","manifest_version":2,"theme":{"images":{"theme_frame":"images\/theme_frame.png","theme_toolbar":"images\/theme_toolbar.png","theme_tab_background":"images\/theme_tab_background.png"},"colors":{"frame":[247,247,247],"toolbar":[247,247,247],"tab_text":[0,0,0],"tab_background_text":[64,64,64],"bookmark_text":[0,0,0],"ntp_background":[255,255,255],"ntp_text":[0,0,0],"button_background":[203,203,203,0.9]},"tints":{"buttons":[0,0,0.44]},"properties":{"ntp_background_alignment":"bottom","ntp_background_repeat":"no-repeat"}}}
```

I changed my Python code to be the following:

```
import eel

web_options = {
	"mode": "chrome-app",
	"host": "localhost",
	"port": 8000,
	"chromeFlags": ["--user-data-dir=theme"]
}
eel.init('web')
eel.start('settings.html', size=(1216, 739), options=web_options)
```

Now my theme folder is full of a bunch of other folders. However, it is not working - the colour is the same. Any ideas?

**Comment by ChrisKnott** [comment]
Unfortunately I don't think this is possible, the `--app` flag seems to override the Theme (at least on Mac it does).

I am eventually hoping to support the Electron frontend/browser which will allow for complete customisation, I think using an existing Chrome installation is only really suitable for prototyping or internal apps.
