### ISSUE TITLE
Eel app size 185mb, taking too long to run 

### ISSUE THREAD

**Issue by shivamjadhav2000** [ChrisKnott/Eel#517]
I have created a desktop app using eel which is turned to be around 185mb , which also might be causing long time to render html and start the app basically, how can I optimize the app and reduce uptime

**Comment by cra2y4ngel** [comment]
check which Python modules you have imported, unnecessary modules will be imported which may be imported by other modules, for example, if you use openpyxl, it will import numpy and pandas , this two packages take about 16MB.

you could read the Documention of pyinstaller to learn how to exclude them. Mostly add the param : --exclude numpy --exclude pandas

**Comment by luciferamji** [comment]
@cra2y4ngel  is correct. You must not be using any separate envs for the same . just make a separe env and install only those modules needed.

**Comment by shivamjadhav2000** [comment]
@cra2y4ngel  I should do that and optimize the app, thanks for the tip , means a lot.
