### ISSUE TITLE
Hello World Hacktoberfest

### ISSUE THREAD

**Issue by gaetan1903** [ChrisKnott/Eel#527]
Can you put hacktoberfest topic in this repos

**Comment by ChrisKnott** [comment]
Sorry I don't know what that means...?

**Comment by gaetan1903** [comment]
https://www.google.com/url?sa=t&source=web&rct=j&url=https://hacktoberfest.digitalocean.com/&ved=2ahUKEwiuhdytoLTzAhULZcAKHX_zBqcQFnoECBUQAQ&usg=AOvVaw3WClc5XFd06zQEPs6Cb6dg

**Comment by ChrisKnott** [comment]
Done
