### ISSUE TITLE
Disable link hover

### ISSUE THREAD

**Issue by 04fsnape** [ChrisKnott/Eel#53]
Hi, I was wondering if it would be possible to remove this little box in the left hand corner that shows up when I hover on a link?

https://pasteboard.co/HqroZbZ.png

Perhaps a chrome flag or something?

**Comment by ChrisKnott** [comment]
@04fsnape After a bit of research, it seems like this isn't possible for security reasons in Chrome. As a workaround you can remove the `href` attribute from your `<a>` tag, then recreate the look with a style, like...

```            .fake-link {
                color: blue;
                cursor: pointer;
                text-decoration: underline;
            }```

And deal with changing pages in the `onclick` handler.
