### ISSUE TITLE
Stopping Asynchronous Python

### ISSUE THREAD

**Issue by tburd** [ChrisKnott/Eel#58]
Thanks and congrats for the great project.
I am starting on python and this helped me a lot.

I am running your assync example and it is working good:

import eel
eel.init('web')

```
def my_other_thread():
    while True:
        print("I'm a thread")
        eel.sleep(1.0)                  # Must use eel.sleep()
    
eel.spawn(my_other_thread)

eel.start('main.html', block=False)     # Don't block on this call

while True:
    print("I'm a main loop")
    eel.sleep(1.0)                      # Must use eel.sleep()

```

Therefore, I need at a certain moment to stop the thread which is running (  eel.spawn(my_other_thread)   ).
I already tried something like:    test = eel.spawn(my_other_thread),   and test.kill() to stop it, but did not work.
How should I do it?

Actually, I am working on a project with some pages. Each page will have some functions that should be running in the background for retrieving new data. But when I switch pages, the other functions should be stopped.
How could I make this easier?

Thank you very much!

**Comment by ChrisKnott** [comment]
@tburd Sorry for not getting back - did you work this out yourself?

**Comment by phuongho43** [comment]
I'm also trying to figure this out. If I do
task = eel.gvt.spawn(my_func)
is there a way to click a button to run task.kill() while my_func is still running?
If I try to run task.kill() via an exposed python function it only executes after my_func is finished.

**Comment by ChrisKnott** [comment]
This is a bug I think, [this line](https://github.com/ChrisKnott/Eel/blob/master/eel/__init__.py#L131) should have a `return`. I will add it to list of bug fixes...
