### ISSUE TITLE
Remove the Border

### ISSUE THREAD

**Issue by Gowixx** [ChrisKnott/Eel#585]
Hey there, is it possible to remove the border on the window?
I am referencing to this:
![image](https://user-images.githubusercontent.com/57415348/164570317-d20f1291-18e9-4fc5-bf2d-76de779f324c.png)

**Comment by THEGOLDENPRO** [comment]
I don't think this is possible with eel or chrome(the browser eel defaults to) but I think this can be done if you use [pywebview](https://github.com/r0x0r/pywebview) as the browser instead. pywebview is a really good and up-to-date python browser module. I've used it with EEL before.

![image](https://user-images.githubusercontent.com/66202304/165496676-2554beee-5924-4bb5-84e3-7c01494496bb.png)

Here's a piece of code to get it up and running.
```python
    def start(self):
        eel_thread = threading.Thread(target=self.eel_start) # Eel app start.
        eel_thread.setDaemon(True)
        eel_thread.start()

        self.webview_start() # Web browser start.

    def eel_start(self, chrome_args):
        # EEL app start.
        eel.start("web/index.html", size=(1200, 680), port=65001, mode=None, shutdown_delay=0.0)

    def webview_start(self):
        webview.create_window('App Name, 'http://localhost:65001/web/index.html', width=1200, height=680, min_size=(1200, 680))
        webview.start(debug=debug, gui="edgechromium")
```

**Comment by Gowixx** [comment]
Could you send the full code? With imports and stuff?

**Comment by THEGOLDENPRO** [comment]
Sorry for leaving this unresponded for a very long while. You've probably already solved this but for future reference here is the full code pretty much.

```python
import webview
import eel
import threading

def start_app():
    eel_thread = threading.Thread(target=eel_start) # Eel app start.
    eel_thread.setDaemon(True)
    eel_thread.start() # Run eel in a seperate thread.

    webview_start() # Start pywebview web browser.

def eel_start():
    # EEL app start.
    eel.start("web/index.html", port=8000, mode=None, shutdown_delay=0.0)

def webview_start():
    # pywebview start.
    webview.create_window("App Name", "http://localhost:8000/web/index.html")
    webview.start()

start_app() # Run app.
```

**Comment by Gowixx** [comment]
Thanks
