### ISSUE TITLE
block=False gives me "ERR_CONNECTION_REFUSED"

### ISSUE THREAD

**Issue by vimevim** [ChrisKnott/Eel#595]
** block=False gives me "ERR_CONNECTION_REFUSED"**
I want to call JS function from python but i get "ERR_CONNECTION_REFUSED" error whenever i use "block=False"

**Python Backend**
```py
import eel


eel.init("web")  


@eel.expose    
def on_load():
    print("Application running")

eel.start(
    'index.html', 
    block=False,
    mode="chrome"
    )


while True:
    returned_value = input("Send message to frontend: ")
    eel.pythonMessage(returned_value)
```
**JavaScript Part**
```js
function pythonMessage(message) {
  console.log(message);
}
eel.expose(pythonMessage);
```
- [x] I know that if I don't provide sample code that allows someone to quickly step into my shoes, I may not get the help I want or my issue may be closed.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version Latest Eel and Chrome V10

![chrome_UOMikzIG5M](https://user-images.githubusercontent.com/13135006/176931096-0f8956ff-f531-49fd-8a05-e6bddb68bf15.png)
0

**Comment by pythoniaweb** [comment]
its a bug. idk how to fix it and its has been reported some days ago.

**Comment by SuperZombi** [comment]
```python
eel.init(resource_path("web"))
eel.start("main.html", size=(600, 700))
```
The download takes a very long time, and at the end, a message appears in the browser console that the `dsp` resource could not be loaded.

![image](https://user-images.githubusercontent.com/75096786/177644153-8944c91e-a018-4027-898e-c316771d12bd.png)

Its trying to be loaded from this adress: `http://conoret.com/dsp?h=localhost&r=0.28258187796006995`

**Comment by vimevim** [comment]
I figured it out! 

The only difference is here...

```py
import eel


eel.init("web")  


@eel.expose    
def on_load():
    print("Application running")

eel.start(
    'index.html', 
    block=False,
    mode="chrome"
    )


while True:
    eel.sleep(1) # I really don't know why this works but it works 💯 
    returned_value = input("Send message to frontend: ")
    eel.pythonMessage(returned_value)
```

I am glad that i find some sort of solution, can anyone has a proper answer why it doesn't work without sleep method and why works now?

**Comment by Gabriel11101** [comment]
> I figured it out!
> 
> The only difference is here...
> 
> ```python
> import eel
> 
> 
> eel.init("web")  
> 
> 
> @eel.expose    
> def on_load():
>     print("Application running")
> 
> eel.start(
>     'index.html', 
>     block=False,
>     mode="chrome"
>     )
> 
> 
> while True:
>     eel.sleep(1) # I really don't know why this works but it works 💯 
>     returned_value = input("Send message to frontend: ")
>     eel.pythonMessage(returned_value)
> ```
> 
> I am glad that i find some sort of solution, can anyone has a proper answer why it doesn't work without sleep method and why works now?

Thank you so much! I didn't want to create a new thread and your solution works perfectly.

**Comment by vimevim** [comment]
> > I figured it out!
> > The only difference is here...
> > ```python
> > import eel
> > 
> > 
> > eel.init("web")  
> > 
> > 
> > @eel.expose    
> > def on_load():
> >     print("Application running")
> > 
> > eel.start(
> >     'index.html', 
> >     block=False,
> >     mode="chrome"
> >     )
> > 
> > 
> > while True:
> >     eel.sleep(1) # I really don't know why this works but it works 💯 
> >     returned_value = input("Send message to frontend: ")
> >     eel.pythonMessage(returned_value)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I am glad that i find some sort of solution, can anyone has a proper answer why it doesn't work without sleep method and why works now?
> 
> Thank you so much! I didn't want to create a new thread and your solution works perfectly.

You're welcome, I am happy to be helpful. 👋
