### ISSUE TITLE
can i run an eel app without a python evironment?

### ISSUE THREAD

**Issue by saintthor** [ChrisKnott/Eel#6]
i hope there is some way.

**Comment by ChrisKnott** [comment]
@saintthor Yes, you can use pyinstaller.

Download pyinstaller with `pip install pyinstaller`
Go to one of the examples and say `pyinstaller file_access.py --hidden-import bottle_websocket --add-data eel.js;eel --noconsole --onefile --exclude pywin32 --exclude pyqt5 --exclude numpy --exclude win32com`

For me this makes a single executable that is ~10MB. You may need to exclude more modules to get the file size down. I am not an expert at pyinstaller

**Comment by ChrisKnott** [comment]
Unfortunately there are actually a couple of issues with this which require changes to the code to work, I will fix them tomorrow.

It should work at the moment if you distribute the 'web' folder along with the exe.

For convenience I've pushed a change so you can say `python -m eel your_script.py --noconsole --onefile`, and it will include the eel.js file automatically

**Comment by saintthor** [comment]
thank you.

**Comment by ChrisKnott** [comment]
@saintthor I've made a change so you can build a single executable file, I've added instructions to the bottom of the README

**Comment by saintthor** [comment]
thanks. i am just considering the technology for some future project.
