### ISSUE TITLE
Cannot import in IDLE anymore

### ISSUE THREAD

**Issue by brentvollebregt** [ChrisKnott/Eel#60]
When trying to execute `import eel` in a script that is run from IDLE (F5), it will become stuck; no errors will appear, it will just hang.
This is occurring on the 0.9.10 and 0.9.9 releases from PyPI. Downgrading to 0.9.7 (0.9.8 was never released)  fixes this issue.
I am currently using Python 3.5.2

**Comment by ChrisKnott** [comment]
@brentvollebregt thanks, I'll look into this. Possibly because I added gevent monkey patching which was required to make some GUI things work

**Comment by brentvollebregt** [comment]
I noticed that, not sure if you use PyCharm but if anyone has an issue with monkey patching in PyCharm, get them to go to Settings -> Build, Execution, Deployment -> Python Debugger and then check "Gevent compatible". 
Just a side note if it comes up; was an issue with recent updates.

**Comment by ChrisKnott** [comment]
I removed monkey patching
