### ISSUE TITLE
Broadcast to all connected clients

### ISSUE THREAD

**Issue by wieger1971** [ChrisKnott/Eel#67]
Great project @ChrisKnott !
Is it possible to somehow emit/broadcast to all connected clients?

I see 2 types of usage:
- from one client to all other clients (excl the sender client)
- from server to all clients

Currently working on a home controller python app and want to broadcast status changes (eg light#1 switched on) to all connected 'remote control' clients so that the UI is updated accordingly. I am now sending own defined JSON packages over web sockets, but your solution is way better!

**Comment by manatlan** [comment]
I don't want to make advertising ...

But it's typically a major difference between eel & wuy.
I wanted this kind of feature too, so I started wuy https://github.com/manatlan/wuy ...
It's a pub/sub mechanism

**Comment by wieger1971** [comment]
Got the tchat server wuy example working. I see that there is the 'emit' function :-)

**Comment by ChrisKnott** [comment]
@manatlan nice stuff, feel free to advertise I don't mind! Looks great

@wieger1971 I think right now this is not possible in eel
