### ISSUE TITLE
Feature Request: Jiinja2 like templating engine

### ISSUE THREAD

**Issue by OmkarPathak** [ChrisKnott/Eel#70]
Eel works like charm. I have made many apps using eel. Thanks for such an awesome package. It would be nice to have some templating engine like Django's Jinja2. Currently, I need to repeat the html headers and footers for each page. To avoid this, can we have some templates?

**Comment by ChrisKnott** [comment]
@OmkarPathak Thank you for your kind feedback, I appreciate it.

Templating is a great idea, it's definitely a problem at the moment that it's a bit messy to build an app that shares a side pane (for example) between screens. We should be able to easily reuse code without repeating it.

I think it should be possible to add Jinja2 support (I can see it works with Bottle e.g. https://buxty.com/b/2013/12/jinja2-templates-and-bottle/) but I really don't know when I am going to get the time to work on it...

I have added it to my todo list though.

**Comment by OmkarPathak** [comment]
@ChrisKnott great to hear that its in your todo list. Let me see if I can get templating thing integrated. If I succeed, I'll be opening a PR soon :smile:

**Comment by sanders41** [comment]
@OmkarPathak have you had any success? I've tried adding an option for jinja templates, but I'm having issues getting bottle to render the templates.

**Comment by OmkarPathak** [comment]
@sanders41 no luck on my side either. Getting rendering issue too!

**Comment by sanders41** [comment]
I was able to get the templates rendering. Now I’m going through testing to make sure everything else works as expected when using templates. If all goes well I’ll open a PR.

**Comment by OmkarPathak** [comment]
@sanders41 that's great. Waiting for your PR 😄

**Comment by ChrisKnott** [comment]
Hi guys, sorry, only just got round to reviewing this. It looks good, I will get it integrated ASAP
