### ISSUE TITLE
How to get values from an HTML button and pass to my python code?

### ISSUE THREAD

**Issue by IronBrotherz** [ChrisKnott/Eel#77]
I want to use Eel for a kiosk interface.  If I have a button for example:

`<button data-id="10">$10.00</button>`

And when its clicked, how can I get the value of "10" and then be able to pass it to my python code that does something with it such as calculating some numbers.

**Comment by thewingit** [comment]
I'm not a real javascript expert, but you can for example use javascript to capture the onClick event of the button and call from javascript an "eel-exposed" Python function and pass the value of the tag "data-id".
Like so: https://repl.it/repls/SpringgreenDeadlyApplicationprogram (it won't work in the shell but you can try it out on your machine)

**Comment by IronBrotherz** [comment]
> I'm not a real javascript expert, but you can for example use javascript to capture the onClick event of the button and call from javascript an "eel-exposed" Python function and pass the value of the tag "data-id".
> Like so: https://repl.it/repls/SpringgreenDeadlyApplicationprogram (it won't work in the shell but you can try it out on your machine)

It worked! thanks so much! With this one example I can move and do so much more as I understand it now. Thank you!

**Comment by ChrisKnott** [comment]
@IronBrotherz thanks for checking out the project, we are very friendly to novice programmers, I am glad you have managed to make progress.

@thewingit thanks for helping out!
