### ISSUE TITLE
How is Eel loading HTML when there is no HTML file, as if its caching

### ISSUE THREAD

**Issue by IronBrotherz** [ChrisKnott/Eel#79]
```
Haroons-MacBook-Pro:eel ironbrotherz$ ls -l
total 16
-rw-r--r--@ 1 ironbrotherz  staff   73 Nov  7 17:56 buy_card.py
-rw-r--r--@ 1 ironbrotherz  staff  334 Nov  7 17:44 index.py
Haroons-MacBook-Pro:eel ironbrotherz$ cat buy_card.py 
import eel

eel.init('web')
eel.start('buy_card.html', size=(1024, 768))
Haroons-MacBook-Pro:eel ironbrotherz$ python buy_card.py 
```

Then a window opens and displays my old buy_card.html page without any styling.  The point is that I deleted my web directory with its others subfolders for css/js/images and somehow its still loading that page.  The issue was that I had my script load index.html and in that web page I have links to local html pages.  When I clicked a button in index.html it loaded my next local page but it was not displaying the updated version of that page after I edited some text.  I was confused so I started deleting stuff and Eel is somehow still opening up stuff that does not exist. I edited the eel script to load buy_card.html which doesnt exist as its been deleted and its still loading the page somehow.

**Comment by ChrisKnott** [comment]
Chrome might be caching it. If you bring up the dev tools with right click -> inspect element, go on network tab, you can tick Disable Cache. Then press CMD+R to reload, see what happens.

Either that or you have another instance of python still running

**Comment by IronBrotherz** [comment]
What you suggested seems to have fixed the issue. Thank you so much for such good support.
