### ISSUE TITLE
Hiding the title bar

### ISSUE THREAD

**Issue by AitorF** [ChrisKnott/Eel#82]
Is is possible to completely hide the title bar to have just the webpage as the application?

**Comment by AitorF** [comment]
Ok. So I assume it's not possible in not-fullscreen mode. Like Spotify do.

**Comment by ChrisKnott** [comment]
Not unless it is a feature of Electron and you use that as the browser

**Comment by MominIqbal-1234** [comment]
what i am add the menu bar in eel window
