### ISSUE TITLE
getting file path

### ISSUE THREAD

**Issue by LogX7** [ChrisKnott/Eel#86]
Hello, i have an input of type file, i want to get the path from the input to my python script, for example electron provides an additional input.files[0].path field that allows for this to happen, since the default web browser path would look like this `c:/fakepath/filename`.

**Comment by brumar** [comment]
I don't think it's possible. The workaround I personally picked is to use the tkinter to do that (https://pythonspot.com/tk-file-dialogs/) . As this is in the standard library, this is not a problematic dependency to manage.

**Comment by ChrisKnott** [comment]
I did the same as @brumar. It's not possible unless you actually do use Electron as the browser

**Comment by ylmazmehmet60** [comment]
For security reasons it is not possible to get the file path through the browser. Using the Tkinter library, you can easily do it as shown in the example below.

**app.py**
```
@eel.expose
def btn_ResimyoluClick():
	root = Tk()
	root.withdraw()
	root.wm_attributes('-topmost', 1)
	folder = filedialog.askdirectory()
	kamera_takip_arayuz.resimyolu = folder
	return folder
```

**main.html**
```
<script>
async function getFolder() {
var dosya_path = await eel.btn_ResimyoluClick()();
	if (dosya_path) {
		console.log(dosya_path);
	}
}
/script>
<a onclick="getFolder()">GetFolder</a>
```

**Comment by brumar** [comment]
I don't know if it's useful for anyone, but a creative alternative could be to use a jquery plug-in ([like this one](https://github.com/jcubic/jquery.filebrowser) to offer the the user an in-browser experience of file choosing. You need to make it call the python back-end so that it gives files and directory name at a given path (by using both `os.listdir(path)` and `os.path.isdir(filepath)`. It's not the easiest path, but depending on you use case, that may fit.

**Comment by LogX7** [comment]
thank you everyone for the amazing responses, i have been using this, i just thought i would open an issue for this to be added.

**Comment by gburlet** [comment]
From the JS side we have the filename, last modified date, and file size in bytes. You can search filesystem on Python side for name match and weed out duplicates based on modified date & file size. Alternatively, you can calculate a checksum hash from the base64 file data on JS side and use that for searching on Python side.
