### ISSUE TITLE
has eel embed chromium?

### ISSUE THREAD

**Issue by top-soft** [ChrisKnott/Eel#90]
It seems that eel does not contain chromium, It calls the local browser engine. Can it be included in the plan to run the target file on the operating system without the browser installed?

**Comment by ChrisKnott** [comment]
Some users have had some success with including Electron. I will make this process more user friendly.

I don't think there is any point in including Chrome/Chromium as it is fundamentally hacky, and it's main advantage is the 2bn+ install base. If you are going to inflate your app from 100kb to 100Mb, might as well include Electron which gives more control.
