### ISSUE TITLE
How can I gracefully exit?

### ISSUE THREAD

**Issue by CombatVolcano** [ChrisKnott/Eel#99]
Is there a 'With' or 'Finally' I can use to exit the browser/connection to it?

I'd also like to say that this is a truly superb project. I went through MANY frameworks trying to find something besides TK when someone finally recommended Eel. It seems so obvious - HTML/CSS is so widely used, well tested and has so many resources for it, and is of course purpose made specifically to be a GUI.
Why would I want to use anything else unless I am required to? 
This is such an excellent project. You did the async work, you documented compiling, you have excellent and basic examples, good documentation, and best of all a truly excellent idea. HATS OFF!!!

**Comment by ChrisKnott** [comment]
@CombatVolcano Thank you for your very kind words.

I am not sure I 100% follow what you are asking... but you don't need to do anything special to cleanly exit. When the last websocket connection to the local server is closed, it will shutdown (by default, you can override this behaviour if you want).

**Comment by subins2000** [comment]
@ChrisKnott How do I override this behaviour ?

**Comment by ChrisKnott** [comment]
@subins2000 You can override the `close_callback` option but it might not give you what you want.

I am currently reviewing a PR that addresses this. I am sorry I have been very busy recently in my job (which is not programming related) so I have lots of issues stacking up for Eel...
